# Site settings
title: gitrit blog
email: 
description: > # this means to ignore newlines until "baseurl:"
  Development news on the gitrit version control education project for RIT.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_organization: gitrit 
github_repository: learn-flow

# Build settings
markdown: kramdown
