# Site settings
title: learnVCS blog
email: 
description: > # this means to ignore newlines until "baseurl:"
  Development news on the learnVCS version control education project for RIT.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "{{baseurl}}" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_organization: learnVCS 
github_repository: learnVCS

# Build settings
markdown: kramdown
