# Site settings
title: learnVCS blog
email: aaronsky@skyaaron.com
description: > # this means to ignore newlines until "baseurl:"
  Development news on the learnVCS version control education project for RIT.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "{{baseurl}}" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_organization: learnVCS 
github_repository: blog

# Build settings
markdown: kramdown
